baseURL = 'https://blog.blackpiratex.com/'
languageCode = 'en-us'
title = 'Blog By BlackPirateX'
theme = 'min-v'


[params]
  author = 'Sudip M.'
  paginate = 15
  subtitle = "Notes, thoughts, and code snippets from my daily life."
  description = "A place for me to write down my thoughts, rants, and reviews."
  tags = 'tags'
  catagories = 'catagories'
[imaging]
  anchor = 'Smart'
  quality = 25
  resampleFilter = 'Box'


[outputs]
  home = ["HTML", "RSS", "JSON"]

[security]
  [security.funcs]
    # Allows the "resources.Get" function we need for the gallery
    get = ["resources"]
    
    

[menu]
  [[menu.main]]
    name = "Github"
    url = "https://github.com/blackpirateapps"
    pre = "github"   # This matches the Lucide icon name
    weight = 10

  [[menu.main]]
    name = "Portfolio"
    url = "https://blackpiratex.com"
    pre = "external-link"
    weight = 20